name: 2 - Deployment to TEST

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'test'
        type: choice
        options:
          - test
      artifact_version:
        description: 'Container version to deploy in Test'
        required: true
        default: 'latest'
      comments:
        description: 'Optional comments'
        required: false

jobs:
  deployContainerInTest:
    name: deploy docker container in Test
    runs-on: ubuntu-latest
    steps:
      - name: Download docker container from docker hub
        run: sleep 3
      - name: Deploy in Test
        run: sleep 3
      - name: Check Deployment Status
        run: echo "Deployment to Test is successful"
