name: 1-DeploymentToTest

on:
  workflow_dispatch:
    inputs:
      artifact_version:
        description: 'Artifact version to deploy'
        required: true
        default: 'latest'
      comments:
        description: 'Optional comments'
        required: false

jobs:
  upload_to_artifactory:
    name: upload_to_artifactory
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 3 seconds
        run: sleep 3
      - name: Wait for 10 seconds
        run: sleep 10
      - name: Check Status
        run: echo "Deployment to Test is successful"
