name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo aByF4bBc#yd3Li67 | docker login -u aablotia --password-stdin

    - name: Build Docker Image
      run: docker build -t aablotia/react-app:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push aablotia/react-app:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH Client
        run: |
          apt update
          apt add --no-cache openssh-client
          chmod 600 $ID_RSA

      - name: Deploy Docker Container
        env:
          DEBIAN_SERVER_USERNAME: aablotia
          DEBIAN_SERVER: 108.17.127.80
          DOCKERHUB_USERNAME: aablotia
          ID_RSA: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACAXblYSWjU5ZCcexjSv/grxqKdqIdTcBJmTjEwCK/VHeAAAAKADFsMgAxbD
            IAAAAAtzc2gtZWQyNTUxOQAAACAXblYSWjU5ZCcexjSv/grxqKdqIdTcBJmTjEwCK/VHeA
            AAAEA5l19qClFIYecFwbHJyUpX2SIcswRYtWFr3fmnwn5j2xduVhJaNTlkJx7GNK/+CvGo
            p2oh1NwEmZOMTAIr9Ud4AAAAF2FhYmxvdGlhQExlbm92b1RoaW5rcGFkAQIDBAUG
            -----END OPENSSH PRIVATE KEY-----

        run:
          echo "Pulling docker image from Dockerhub ....................................................."
          ssh -i $ID_RSA -o StrictHostKeyChecking=no $DEBIAN_SERVER_USERNAME@$DEBIAN_SERVER "docker pull ${DOCKERHUB_USERNAME}/${ARTIFACT_ID}:latest"
          
          echo "Stopping application infohub in docker container ....................................................."
          ssh -i $ID_RSA -o StrictHostKeyChecking=no $DEBIAN_SERVER_USERNAME@$DEBIAN_SERVER "docker stop infohub || true"
          ssh -i $ID_RSA -o StrictHostKeyChecking=no $DEBIAN_SERVER_USERNAME@$DEBIAN_SERVER "docker rm infohub || true"

          echo "Running application in docker container ....................................................."
          ssh -i $ID_RSA -o StrictHostKeyChecking=no $DEBIAN_SERVER_USERNAME@$DEBIAN_SERVER "docker run -d --network="host" --name infohub ${DOCKERHUB_USERNAME}/${ARTIFACT_ID}:latest"



